"""test running migrations

Revision ID: 8bc9af07f3a8
Revises:
Create Date: 2025-10-05 19:39:38.748936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
# pragma: allowlist secret
revision: str = "8bc9af07f3a8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "types_package",
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("type_id"),
    )
    op.create_table(
        "parcels",
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("price_delivery", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["types_package.type_id"],
        ),
        sa.PrimaryKeyConstraint("package_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parcels")
    op.drop_table("types_package")
    # ### end Alembic commands ###
