"""comment

Revision ID: 58c38e1a7557
Revises: df56872200ac
Create Date: 2025-09-23 09:53:28.810438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c38e1a7557'
down_revision: Union[str, Sequence[str], None] = 'df56872200ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('type_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('parcels_type_package_fkey'), 'parcels', type_='foreignkey')
    op.create_foreign_key(None, 'parcels', 'types_package', ['type_id'], ['type_id'])
    op.drop_column('parcels', 'type_package')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('type_package', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'parcels', type_='foreignkey')
    op.create_foreign_key(op.f('parcels_type_package_fkey'), 'parcels', 'types_package', ['type_package'], ['type_id'])
    op.drop_column('parcels', 'type_id')
    # ### end Alembic commands ###
