"""comment

Revision ID: df56872200ac
Revises: 9f0b29223ba1
Create Date: 2025-09-23 09:14:35.761129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df56872200ac"
down_revision: Union[str, Sequence[str], None] = "9f0b29223ba1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcels", sa.Column("price_delivery", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parcels", "price_delivery")
    # ### end Alembic commands ###
